---
- name: exercise 1
  hosts: arista
  
  tasks:
    - name: Configure VLANs
      eos_switchport: name={{ item.intname }} description="{{ item.desc }}" mode={{ item.mode}} access_vlan={{ item.access_vlan }}
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
        - {intname: Ethernet3, desc: "*** IN USE*** ", mode: access, access_vlan: 725}
