---
- name: exercise 2
  hosts: arista
  
  tasks:
    - name: Configure interface
      eos_interface: name={{ item.intname }} description="{{ item.desc }}"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
        - {intname: Ethernet3, desc: "*** IN USE***"}

        
    - name: Configure switchport
      eos_switchport: name={{ item.intname }} mode={{ item.mode}} trunk_native_vlan={{ item.trunk_native_vlan }} 
                      trunk_allowed_vlans={{ item.trunk_allowed_vlans }}
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
        - {intname: Ethernet3, mode: trunk, trunk_native_vlan: 1, trunk_allowed_vlans: 723,724,725}
